### ISSUE TITLE
Error in `[[.partynode`(x, v) : ‘x’ is incorrect node

### ISSUE THREAD

**Issue by Geoffrey-Guest** [Displayr/rhtmlSankeyTree#3]
I followed your directions but your example did not work for me. Do you know why I get this error (do I need to install something else?):

# convert rpart to a hierarchy using convert_rpart in converters.R
> rhtmlSankeyTree:::convert_rpart(rp)
Error in `[[.partynode`(x, v) : ‘x’ is incorrect node
> 
> #see what it looks like
> SankeyTree(rp)
Error in `[[.partynode`(x, v) : ‘x’ is incorrect node
>

**Comment by kocman** [comment]
Hello Geoffrey, could you find a solution? I have the same issue

**Comment by Geoffrey-Guest** [comment]
Hey unfortunately not yet. I sort of let it go for now.

**Comment by JustinCCYap** [comment]
Hi guys, according to a comment in the function, "This thing is not even close to being done.". It looks like it has kind of been forgotten and isn't currently in use. I would suggest checking out rPartToTreeFrame and treeFrameToList in Displayr/flipTrees.

**Comment by kocman** [comment]
Hello JustinCCYAP,
thank you for the Information! 
The package Displayr/flipTrees which you recommended supports a beautiful sankeyTree with the following example command
`CART(Kyphosis ~ Age + Number + Start, data = kyphosis)`
Do you khow how to get this plot in a shiny app? I dont know how to handle this command in the renderfunction in Shiny. Would be a realy big help :)

**Comment by JustinCCYap** [comment]
Hi kocman,
I don't have experience with Shiny and this repo hasn't been tested in Shiny so I'm not able to help you unfortunately.
